name: probtest-dev
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - alabaster=0.7.12
  - alsa-lib=1.2.8
  - appdirs=1.4.4
  - astroid=2.13.2
  - asttokens=2.2.1
  - attr=2.5.1
  - attrs=22.2.0
  - babel=2.11.0
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - black=22.10.0
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2022.12.7
  - certifi=2022.12.7
  - cffi=1.15.1
  - cfgv=3.3.1
  - cftime=1.6.2
  - charset-normalizer=2.1.1
  - click=8.1.3
  - codespell=2.2.2
  - colorama=0.4.6
  - contourpy=1.0.6
  - cryptography=39.0.0
  - curl=7.87.0
  - cycler=0.11.0
  - dbus=1.13.6
  - decorator=5.1.1
  - dill=0.3.6
  - distlib=0.3.6
  - docutils=0.17.1
  - exceptiongroup=1.1.0
  - executing=1.2.0
  - expat=2.5.0
  - fftw=3.3.10
  - filelock=3.9.0
  - flake8=6.0.0
  - flake8-black=0.3.5
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.1
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.38.0
  - freetype=2.12.1
  - gettext=0.21.1
  - glib=2.74.1
  - glib-tools=2.74.1
  - gst-plugins-base=1.21.3
  - gstreamer=1.21.3
  - gstreamer-orc=0.4.33
  - hdf4=4.2.15
  - hdf5=1.12.2
  - icu=70.1
  - identify=2.5.12
  - idna=3.4
  - imagesize=1.4.1
  - importlib-metadata=3.3.0
  - iniconfig=2.0.0
  - ipdb=0.13.11
  - ipython=8.8.0
  - isort=5.11.4
  - jack=1.9.21
  - jedi=0.18.2
  - jinja2=3.1.2
  - jpeg=9e
  - keyutils=1.6.1
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lame=3.100
  - lazy-object-proxy=1.9.0
  - lcms2=2.14
  - ld_impl_linux-64=2.39
  - lerc=4.0.0
  - libaec=1.0.6
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcap=2.66
  - libcblas=3.9.0
  - libclang=15.0.6
  - libclang13=15.0.6
  - libcups=2.3.3
  - libcurl=7.87.0
  - libdb=6.2.32
  - libdeflate=1.14
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.10
  - libffi=3.4.2
  - libflac=1.4.2
  - libgcc-ng=12.2.0
  - libgcrypt=1.10.1
  - libgfortran-ng=12.2.0
  - libgfortran5=12.2.0
  - libglib=2.74.1
  - libgomp=12.2.0
  - libgpg-error=1.46
  - libiconv=1.17
  - libjpeg-turbo=2.1.4
  - liblapack=3.9.0
  - libllvm15=15.0.6
  - libnetcdf=4.8.1
  - libnghttp2=1.51.0
  - libnsl=2.0.0
  - libogg=1.3.4
  - libopenblas=0.3.21
  - libopus=1.3.1
  - libpng=1.6.39
  - libpq=15.1
  - libsndfile=1.1.0
  - libsqlite=3.40.0
  - libssh2=1.10.0
  - libstdcxx-ng=12.2.0
  - libsystemd0=252
  - libtiff=4.5.0
  - libtool=2.4.7
  - libudev1=252
  - libuuid=2.32.1
  - libvorbis=1.3.7
  - libwebp-base=1.2.4
  - libxcb=1.13
  - libxkbcommon=1.0.3
  - libxml2=2.10.3
  - libzip=1.9.2
  - libzlib=1.2.13
  - livereload=2.6.3
  - lz4-c=1.9.3
  - markupsafe=2.1.1
  - matplotlib=3.6.2
  - matplotlib-base=3.6.2
  - matplotlib-inline=0.1.6
  - mccabe=0.7.0
  - mpg123=1.31.1
  - munkres=1.1.4
  - mypy=0.991
  - mypy_extensions=0.4.3
  - mysql-common=8.0.31
  - mysql-libs=8.0.31
  - ncurses=6.3
  - netcdf4=1.6.2
  - nodeenv=1.7.0
  - nspr=4.35
  - nss=3.82
  - numpy=1.24.1
  - openjpeg=2.5.0
  - openssl=3.0.7
  - packaging=22.0
  - pandas=1.5.2
  - parso=0.8.3
  - pathlib=1.0.1
  - pathspec=0.10.3
  - pcre2=10.40
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.4.0
  - pip=22.3.1
  - platformdirs=2.6.2
  - pluggy=1.0.0
  - ply=3.11
  - pooch=1.6.0
  - pre-commit=2.21.0
  - pre-commit-hooks=4.4.0
  - prompt-toolkit=3.0.36
  - psutil=5.9.4
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pulseaudio=16.1
  - pure_eval=0.2.2
  - pycodestyle=2.10.0
  - pycparser=2.21
  - pydantic=1.10.4
  - pydocstyle=6.2.2
  - pyflakes=3.0.1
  - pygments=2.14.0
  - pylint=2.15.10
  - pyopenssl=23.0.0
  - pyparsing=3.0.9
  - pyqt=5.15.7
  - pyqt5-sip=12.11.0
  - pysocks=1.7.1
  - pytest=7.2.0
  - python=3.11.0
  - python-dateutil=2.8.2
  - python_abi=3.11
  - pytoolconfig=1.2.4
  - pytz=2022.7
  - pyyaml=6.0
  - qt-main=5.15.6
  - readline=8.1.2
  - regex=2022.10.31
  - requests=2.28.1
  - rope=1.6.0
  - rstcheck=6.1.1
  - rstcheck-core=1.0.2
  - ruamel.yaml=0.17.21
  - ruamel.yaml.clib=0.2.7
  - scipy=1.10.0
  - setuptools=65.6.3
  - shellingham=1.5.0.post1
  - sip=6.7.5
  - six=1.16.0
  - snowballstemmer=2.2.0
  - sphinx=4.3.2
  - sphinx-autobuild=2021.3.14
  - sphinxcontrib-applehelp=1.0.2
  - sphinxcontrib-devhelp=1.0.2
  - sphinxcontrib-htmlhelp=2.0.0
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=1.0.3
  - sphinxcontrib-serializinghtml=1.1.5
  - stack_data=0.6.2
  - tk=8.6.12
  - toml=0.10.2
  - tomli=2.0.1
  - tomlkit=0.11.6
  - tornado=6.2
  - traitlets=5.8.1
  - typer=0.4.2
  - types-docutils=0.18.3
  - typing=3.10.0.0
  - typing-extensions=4.4.0
  - typing_extensions=4.4.0
  - tzdata=2022g
  - ukkonen=1.0.1
  - urllib3=1.26.13
  - virtualenv=20.17.1
  - wcwidth=0.2.5
  - wheel=0.38.4
  - wrapt=1.14.1
  - xarray=2022.12.0
  - xcb-util=0.4.0
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.0
  - xcb-util-renderutil=0.3.9
  - xcb-util-wm=0.4.1
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xz=5.2.6
  - yaml=0.2.5
  - zipp=3.11.0
  - zlib=1.2.13
  - zstd=1.5.2
  - earthkit-data
  - pip:
      - flake8-pyproject==1.2.2
