name: probtest
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - alsa-lib=1.2.14
  - annotated-types=0.7.0
  - astroid=3.3.10
  - asttokens=3.0.0
  - black=25.1.0
  - blosc=1.21.6
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.6.15
  - cairo=1.18.4
  - certifi=2025.6.15
  - cffi=1.17.1
  - cfgv=3.3.1
  - cftime=1.6.4
  - click=8.2.1
  - codespell=2.4.1
  - colorama=0.4.6
  - contourpy=1.3.2
  - cycler=0.12.1
  - cyrus-sasl=2.1.28
  - dbus=1.16.2
  - decorator=5.2.1
  - dill=0.4.0
  - distlib=0.3.9
  - docutils=0.21.2
  - double-conversion=3.3.1
  - exceptiongroup=1.3.0
  - executing=2.2.0
  - filelock=3.18.0
  - flake8=7.2.0
  - flake8-black=0.3.6
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.58.4
  - freetype=2.13.3
  - graphite2=1.3.14
  - harfbuzz=11.2.1
  - hdf4=4.2.15
  - hdf5=1.14.6
  - icu=75.1
  - identify=2.6.12
  - importlib-metadata=8.7.0
  - iniconfig=2.0.0
  - ipdb=0.13.13
  - ipython=8.37.0
  - isort=6.0.1
  - jedi=0.19.2
  - jinja2=3.1.6
  - keyutils=1.6.1
  - kiwisolver=1.4.7
  - krb5=1.21.3
  - lcms2=2.17
  - ld_impl_linux-64=2.43
  - lerc=4.0.0
  - libaec=1.1.4
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libclang-cpp20.1=20.1.7
  - libclang13=20.1.7
  - libcups=2.3.3
  - libcurl=8.14.1
  - libdeflate=1.24
  - libdrm=2.4.125
  - libedit=3.1.20250104
  - libegl=1.7.0
  - libev=4.33
  - libexpat=2.7.0
  - libffi=3.4.6
  - libfreetype=2.13.3
  - libfreetype6=2.13.3
  - libgcc=15.1.0
  - libgcc-ng=15.1.0
  - libgfortran=15.1.0
  - libgfortran5=15.1.0
  - libgl=1.7.0
  - libglib=2.84.2
  - libglvnd=1.7.0
  - libglx=1.7.0
  - libgomp=15.1.0
  - libiconv=1.18
  - libjpeg-turbo=3.1.0
  - liblapack=3.9.0
  - libllvm20=20.1.7
  - liblzma=5.8.1
  - liblzma-devel=5.8.1
  - libnetcdf=4.9.2
  - libnghttp2=1.64.0
  - libnsl=2.0.1
  - libntlm=1.8
  - libopenblas=0.3.30
  - libopengl=1.7.0
  - libpciaccess=0.18
  - libpng=1.6.49
  - libpq=17.5
  - libsqlite=3.50.1
  - libssh2=1.11.1
  - libstdcxx=15.1.0
  - libstdcxx-ng=15.1.0
  - libtiff=4.7.0
  - libuuid=2.38.1
  - libwebp-base=1.5.0
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libxkbcommon=1.10.0
  - libxml2=2.13.8
  - libxslt=1.1.39
  - libzip=1.11.2
  - libzlib=1.3.1
  - lz4-c=1.10.0
  - markdown-it-py=3.0.0
  - markupsafe=3.0.2
  - matplotlib=3.10.3
  - matplotlib-base=3.10.3
  - matplotlib-inline=0.1.7
  - mccabe=0.7.0
  - mdurl=0.1.2
  - munkres=1.1.4
  - mypy=1.16.1
  - mypy_extensions=1.1.0
  - ncurses=6.5
  - netcdf4=1.7.2
  - nodeenv=1.9.1
  - numpy=2.2.6
  - openjpeg=2.5.3
  - openldap=2.6.10
  - openssl=3.5.0
  - packaging=25.0
  - pandas=2.3.0
  - parso=0.8.4
  - pathlib=1.0.1
  - pathspec=0.12.1
  - pcre2=10.45
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=11.2.1
  - pip=25.1.1
  - pixman=0.46.2
  - platformdirs=4.3.8
  - pluggy=1.6.0
  - pre-commit=4.2.0
  - pre-commit-hooks=5.0.0
  - prompt-toolkit=3.0.51
  - psutil=7.0.0
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pycodestyle=2.13.0
  - pycparser=2.22
  - pydantic=2.11.7
  - pydantic-core=2.33.2
  - pydocstyle=6.3.0
  - pyflakes=3.3.2
  - pygments=2.19.1
  - pylint=3.3.7
  - pyparsing=3.2.3
  - pyside6=6.9.1
  - pytest=8.4.1
  - python=3.10.8
  - python-dateutil=2.9.0.post0
  - python-tzdata=2025.2
  - python_abi=3.10
  - pytoolconfig=1.2.5
  - pytz=2025.2
  - pyyaml=6.0.2
  - qhull=2020.2
  - qt6-main=6.9.1
  - readline=8.2
  - regex=2024.11.6
  - rich=14.0.0
  - rope=1.13.0
  - rstcheck=6.2.4
  - rstcheck-core=1.2.1
  - ruamel.yaml=0.18.14
  - ruamel.yaml.clib=0.2.8
  - scipy=1.15.2
  - setuptools=80.9.0
  - shellingham=1.5.4
  - six=1.17.0
  - snappy=1.2.1
  - snowballstemmer=3.0.1
  - stack_data=0.6.3
  - tk=8.6.13
  - toml=0.10.2
  - tomli=2.2.1
  - tomlkit=0.13.3
  - tornado=6.5.1
  - traitlets=5.14.3
  - typer=0.16.0
  - typer-slim=0.16.0
  - typer-slim-standard=0.16.0
  - typing-extensions=4.14.0
  - typing-inspection=0.4.1
  - typing_extensions=4.14.0
  - tzdata=2025b
  - ukkonen=1.0.1
  - unicodedata2=16.0.0
  - virtualenv=20.31.2
  - wayland=1.23.1
  - wcwidth=0.2.13
  - wheel=0.45.1
  - xarray=2025.6.1
  - xcb-util=0.4.1
  - xcb-util-cursor=0.1.5
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.1
  - xcb-util-renderutil=0.3.10
  - xcb-util-wm=0.4.2
  - xkeyboard-config=2.45
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxcomposite=0.4.6
  - xorg-libxcursor=1.2.3
  - xorg-libxdamage=1.1.6
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxfixes=6.0.1
  - xorg-libxi=1.8.2
  - xorg-libxrandr=1.5.4
  - xorg-libxrender=0.9.12
  - xorg-libxtst=1.2.5
  - xorg-libxxf86vm=1.1.6
  - xz=5.8.1
  - xz-gpl-tools=5.8.1
  - xz-tools=5.8.1
  - yaml=0.2.5
  - zipp=3.23.0
  - zlib=1.3.1
  - zstd=1.5.7
  - pip:
      - coverage==7.9.1
      - flake8-pyproject==1.2.3
      - pytest-cov==6.2.1
