name: probtest
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - annotated-types=0.7.0
  - astroid=3.3.4
  - asttokens=2.4.1
  - attrs=24.2.0
  - aws-c-auth=0.7.22
  - aws-c-cal=0.6.14
  - aws-c-common=0.9.19
  - aws-c-compression=0.2.18
  - aws-c-event-stream=0.4.2
  - aws-c-http=0.8.1
  - aws-c-io=0.14.8
  - aws-c-mqtt=0.10.4
  - aws-c-s3=0.5.9
  - aws-c-sdkutils=0.1.16
  - aws-checksums=0.1.18
  - aws-crt-cpp=0.26.9
  - aws-sdk-cpp=1.11.329
  - black=24.8.0
  - bokeh=3.5.2
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.33.1
  - ca-certificates=2024.8.30
  - certifi=2024.8.30
  - cffi=1.17.1
  - cfgrib=0.9.14.1
  - cfgv=3.3.1
  - cftime=1.6.4
  - charset-normalizer=3.3.2
  - click=8.1.7
  - cloudpickle=3.0.0
  - codespell=2.3.0
  - colorama=0.4.6
  - contourpy=1.3.0
  - curl=8.9.1
  - cycler=0.12.1
  - cytoolz=0.12.3
  - dask=2024.9.1
  - dask-core=2024.9.1
  - dask-expr=1.1.15
  - dbus=1.13.18
  - decorator=5.1.1
  - dill=0.3.9
  - distlib=0.3.8
  - distributed=2024.9.1
  - docutils=0.21.2
  - earthkit-data=0.5.6
  - eccodes=2.25.0
  - entrypoints=0.4
  - exceptiongroup=1.2.2
  - executing=2.1.0
  - expat=2.6.3
  - filelock=3.16.1
  - findlibs=0.0.5
  - flake8=7.1.1
  - flake8-black=0.3.6
  - fontconfig=2.14.2
  - fonttools=4.54.1
  - freeglut=3.2.2
  - freetype=2.12.1
  - fsspec=2024.9.0
  - gflags=2.2.2
  - glib=2.80.2
  - glib-tools=2.80.2
  - glog=0.7.1
  - gst-plugins-base=1.14.1
  - gstreamer=1.14.1
  - h2=4.1.0
  - hdf4=4.2.15
  - hdf5=1.12.1
  - hpack=4.0.0
  - hyperframe=6.0.1
  - icu=73.2
  - identify=2.6.1
  - idna=3.10
  - importlib-metadata=8.5.0
  - importlib_metadata=8.5.0
  - iniconfig=2.0.0
  - ipdb=0.13.13
  - ipython=8.28.0
  - isort=5.13.2
  - jasper=2.0.33
  - jedi=0.19.1
  - jinja2=3.1.4
  - jpeg=9e
  - keyutils=1.6.1
  - kiwisolver=1.4.7
  - krb5=1.20.1
  - lcms2=2.12
  - ld_impl_linux-64=2.43
  - lerc=3.0
  - libabseil=20240116.2
  - libaec=1.1.3
  - libarrow=16.1.0
  - libarrow-acero=16.1.0
  - libarrow-dataset=16.1.0
  - libarrow-substrait=16.1.0
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libclang=14.0.6
  - libclang13=14.0.6
  - libcrc32c=1.1.2
  - libcups=2.3.3
  - libcurl=8.9.1
  - libdeflate=1.10
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.6.3
  - libffi=3.4.2
  - libgcc=14.1.0
  - libgcc-ng=14.1.0
  - libgfortran=14.1.0
  - libgfortran-ng=14.1.0
  - libgfortran5=14.1.0
  - libglib=2.80.2
  - libglu=9.0.0
  - libgomp=14.1.0
  - libgoogle-cloud=2.24.0
  - libgoogle-cloud-storage=2.24.0
  - libgrpc=1.62.2
  - libiconv=1.17
  - liblapack=3.9.0
  - libllvm14=14.0.6
  - libnetcdf=4.8.1
  - libnghttp2=1.58.0
  - libnsl=2.0.1
  - libopenblas=0.3.27
  - libparquet=16.1.0
  - libpng=1.6.43
  - libpq=12.17
  - libprotobuf=4.25.3
  - libre2-11=2023.09.01
  - libsqlite=3.46.0
  - libssh2=1.11.0
  - libstdcxx=14.1.0
  - libstdcxx-ng=14.1.0
  - libthrift=0.19.0
  - libtiff=4.3.0
  - libutf8proc=2.8.0
  - libuuid=2.38.1
  - libwebp-base=1.4.0
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libxkbcommon=1.7.0
  - libxml2=2.12.7
  - libzip=1.10.1
  - libzlib=1.2.13
  - locket=1.0.0
  - lz4=4.3.3
  - lz4-c=1.9.4
  - markdown-it-py=3.0.0
  - markupsafe=2.1.5
  - matplotlib=3.9.1
  - matplotlib-base=3.9.1
  - matplotlib-inline=0.1.7
  - mccabe=0.7.0
  - mdurl=0.1.2
  - msgpack-python=1.1.0
  - munkres=1.1.4
  - mypy=1.11.2
  - mypy_extensions=1.0.0
  - mysql=5.7.20
  - ncurses=6.5
  - netcdf4=1.6.0
  - nodeenv=1.9.1
  - numpy=1.26.4
  - olefile=0.47
  - openjpeg=2.5.0
  - openssl=3.3.2
  - orc=2.0.1
  - packaging=24.1
  - pandas=2.2.3
  - parso=0.8.4
  - partd=1.4.2
  - pathlib=1.0.1
  - pathspec=0.12.1
  - pcre2=10.43
  - pdbufr=0.11.0
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=8.4.0
  - pip=24.2
  - platformdirs=4.3.6
  - pluggy=1.5.0
  - pre-commit=3.8.0
  - pre-commit-hooks=4.6.0
  - prompt-toolkit=3.0.48
  - psutil=6.0.0
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pyarrow=16.1.0
  - pyarrow-core=16.1.0
  - pyarrow-hotfix=0.6
  - pycodestyle=2.12.1
  - pycparser=2.22
  - pydantic=2.9.2
  - pydantic-core=2.23.4
  - pydocstyle=6.3.0
  - pyflakes=3.2.0
  - pygments=2.18.0
  - pylint=3.3.1
  - pyparsing=3.1.4
  - pyqt=5.15.4
  - pyqt5-sip=12.9.0
  - pysocks=1.7.1
  - pytest=8.3.3
  - python=3.10.14
  - python-dateutil=2.9.0
  - python-eccodes=1.4.0
  - python-tzdata=2024.2
  - python_abi=3.10
  - pytoolconfig=1.2.5
  - pytz=2024.1
  - pyyaml=6.0.2
  - qhull=2020.2
  - qt-main=5.15.2
  - re2=2023.09.01
  - readline=8.2
  - regex=2024.9.11
  - requests=2.32.3
  - rich=13.9.1
  - rope=1.13.0
  - rstcheck=6.2.4
  - rstcheck-core=1.2.1
  - ruamel.yaml=0.18.6
  - ruamel.yaml.clib=0.2.8
  - s2n=1.4.15
  - scipy=1.14.1
  - setuptools=75.1.0
  - shellingham=1.5.4
  - sip=6.5.1
  - six=1.16.0
  - snappy=1.2.1
  - snowballstemmer=2.2.0
  - sortedcontainers=2.4.0
  - sqlite=3.46.0
  - stack_data=0.6.2
  - tblib=3.0.0
  - tk=8.6.13
  - toml=0.10.2
  - tomli=2.0.2
  - tomlkit=0.13.2
  - toolz=0.12.1
  - tornado=6.4.1
  - tqdm=4.66.5
  - traitlets=5.14.3
  - typer=0.12.5
  - typer-slim=0.12.5
  - typer-slim-standard=0.12.5
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - tzdata=2024a
  - ukkonen=1.0.1
  - unicodedata2=15.1.0
  - urllib3=2.2.3
  - virtualenv=20.26.6
  - wcwidth=0.2.13
  - wheel=0.44.0
  - xarray=2024.9.0
  - xkeyboard-config=2.43
  - xorg-libx11=1.8.10
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxfixes=6.0.1
  - xorg-libxi=1.8.2
  - xorg-xextproto=7.3.0
  - xorg-xorgproto=2024.1
  - xyzservices=2024.9.0
  - xz=5.2.6
  - yaml=0.2.5
  - zict=3.0.0
  - zipp=3.20.2
  - zlib=1.2.13
  - zstandard=0.23.0
  - zstd=1.5.6
  - pip:
      - coverage==7.6.1
      - flake8-pyproject==1.2.3
      - pytest-cov==5.0.0
