name: probtest
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - alsa-lib=1.2.12
  - annotated-types=0.7.0
  - astroid=3.3.5
  - asttokens=2.4.1
  - attrs=24.2.0
  - aws-c-auth=0.8.0
  - aws-c-cal=0.8.0
  - aws-c-common=0.10.0
  - aws-c-compression=0.3.0
  - aws-c-event-stream=0.5.0
  - aws-c-http=0.9.0
  - aws-c-io=0.15.0
  - aws-c-mqtt=0.11.0
  - aws-c-s3=0.7.0
  - aws-c-sdkutils=0.2.0
  - aws-checksums=0.2.0
  - aws-crt-cpp=0.29.1
  - aws-sdk-cpp=1.11.407
  - azure-core-cpp=1.14.0
  - azure-identity-cpp=1.10.0
  - azure-storage-blobs-cpp=12.13.0
  - azure-storage-common-cpp=12.8.0
  - azure-storage-files-datalake-cpp=12.12.0
  - black=24.10.0
  - blosc=1.21.6
  - bokeh=3.6.1
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.34.2
  - ca-certificates=2024.8.30
  - cairo=1.18.0
  - certifi=2024.8.30
  - cffi=1.17.1
  - cfgrib=0.9.14.1
  - cfgv=3.3.1
  - cftime=1.6.4
  - charset-normalizer=3.4.0
  - click=8.1.7
  - cloudpickle=3.1.0
  - codespell=2.3.0
  - colorama=0.4.6
  - contourpy=1.3.0
  - cycler=0.12.1
  - cyrus-sasl=2.1.27
  - cytoolz=1.0.0
  - dask=2024.10.0
  - dask-core=2024.10.0
  - dask-expr=1.1.16
  - dbus=1.13.6
  - decorator=5.1.1
  - dill=0.3.9
  - distlib=0.3.9
  - distributed=2024.10.0
  - docutils=0.21.2
  - double-conversion=3.3.0
  - earthkit-data=0.5.6
  - eccodes=2.33.0
  - entrypoints=0.4
  - exceptiongroup=1.2.2
  - executing=2.1.0
  - expat=2.6.4
  - filelock=3.16.1
  - findlibs=0.0.5
  - flake8=7.1.1
  - flake8-black=0.3.6
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.54.1
  - freeglut=3.2.2
  - freetype=2.12.1
  - fsspec=2024.10.0
  - gflags=2.2.2
  - glog=0.7.1
  - graphite2=1.3.13
  - h2=4.1.0
  - harfbuzz=9.0.0
  - hdf4=4.2.15
  - hdf5=1.14.3
  - hpack=4.0.0
  - hyperframe=6.0.1
  - icu=75.1
  - identify=2.6.1
  - idna=3.10
  - importlib-metadata=8.5.0
  - importlib_metadata=8.5.0
  - iniconfig=2.0.0
  - ipdb=0.13.13
  - ipython=8.29.0
  - isort=5.13.2
  - jasper=4.2.4
  - jedi=0.19.1
  - jinja2=3.1.4
  - keyutils=1.6.1
  - kiwisolver=1.4.7
  - krb5=1.21.3
  - lcms2=2.16
  - ld_impl_linux-64=2.43
  - lerc=4.0.0
  - libabseil=20240722.0
  - libaec=1.1.3
  - libarrow=18.0.0
  - libarrow-acero=18.0.0
  - libarrow-dataset=18.0.0
  - libarrow-substrait=18.0.0
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libclang-cpp19.1=19.1.3
  - libclang13=19.1.3
  - libcrc32c=1.1.2
  - libcups=2.3.3
  - libcurl=8.11.0
  - libdeflate=1.22
  - libdrm=2.4.123
  - libedit=3.1.20191231
  - libegl=1.7.0
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.6.4
  - libffi=3.4.2
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgfortran=14.2.0
  - libgfortran-ng=14.2.0
  - libgfortran5=14.2.0
  - libgl=1.7.0
  - libglib=2.82.2
  - libglu=9.0.0
  - libglvnd=1.7.0
  - libglx=1.7.0
  - libgomp=14.2.0
  - libgoogle-cloud=2.30.0
  - libgoogle-cloud-storage=2.30.0
  - libgrpc=1.67.1
  - libiconv=1.17
  - libjpeg-turbo=3.0.0
  - liblapack=3.9.0
  - libllvm19=19.1.3
  - libnetcdf=4.9.2
  - libnghttp2=1.64.0
  - libnsl=2.0.1
  - libntlm=1.4
  - libopenblas=0.3.28
  - libopengl=1.7.0
  - libparquet=18.0.0
  - libpciaccess=0.18
  - libpng=1.6.44
  - libpq=17.0
  - libprotobuf=5.28.2
  - libre2-11=2024.07.02
  - libsqlite=3.47.0
  - libssh2=1.11.0
  - libstdcxx=14.2.0
  - libstdcxx-ng=14.2.0
  - libthrift=0.21.0
  - libtiff=4.7.0
  - libutf8proc=2.8.0
  - libuuid=2.38.1
  - libwebp-base=1.4.0
  - libxcb=1.17.0
  - libxkbcommon=1.7.0
  - libxml2=2.13.4
  - libxslt=1.1.39
  - libzip=1.11.2
  - libzlib=1.3.1
  - locket=1.0.0
  - lz4=4.3.3
  - lz4-c=1.9.4
  - markdown-it-py=3.0.0
  - markupsafe=3.0.2
  - matplotlib=3.9.2
  - matplotlib-base=3.9.2
  - matplotlib-inline=0.1.7
  - mccabe=0.7.0
  - mdurl=0.1.2
  - msgpack-python=1.1.0
  - munkres=1.1.4
  - mypy=1.13.0
  - mypy_extensions=1.0.0
  - mysql-common=9.0.1
  - mysql-libs=9.0.1
  - ncurses=6.5
  - netcdf4=1.7.1
  - nodeenv=1.9.1
  - numpy=2.1.3
  - openjpeg=2.5.2
  - openldap=2.6.8
  - openssl=3.3.2
  - orc=2.0.2
  - packaging=24.1
  - pandas=2.2.3
  - parso=0.8.4
  - partd=1.4.2
  - pathlib=1.0.1
  - pathspec=0.12.1
  - pcre2=10.44
  - pdbufr=0.11.0
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=11.0.0
  - pip=24.3.1
  - pixman=0.43.2
  - platformdirs=4.3.6
  - pluggy=1.5.0
  - pre-commit=4.0.1
  - pre-commit-hooks=5.0.0
  - prompt-toolkit=3.0.48
  - psutil=6.1.0
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pyarrow=18.0.0
  - pyarrow-core=18.0.0
  - pycodestyle=2.12.1
  - pycparser=2.22
  - pydantic=2.9.2
  - pydantic-core=2.23.4
  - pydocstyle=6.3.0
  - pyflakes=3.2.0
  - pygments=2.18.0
  - pylint=3.3.1
  - pyparsing=3.2.0
  - pyside6=6.8.0.2
  - pysocks=1.7.1
  - pytest=8.3.3
  - python=3.10.8
  - python-dateutil=2.9.0
  - python-eccodes=1.7.1
  - python-tzdata=2024.2
  - python_abi=3.10
  - pytoolconfig=1.2.5
  - pytz=2024.1
  - pyyaml=6.0.2
  - qhull=2020.2
  - qt6-main=6.8.0
  - re2=2024.07.02
  - readline=8.2
  - regex=2024.11.6
  - requests=2.32.3
  - rich=13.9.4
  - rope=1.13.0
  - rstcheck=6.2.4
  - rstcheck-core=1.2.1
  - ruamel.yaml=0.18.6
  - ruamel.yaml.clib=0.2.8
  - s2n=1.5.6
  - scipy=1.14.1
  - setuptools=75.3.0
  - shellingham=1.5.4
  - six=1.16.0
  - snappy=1.2.1
  - snowballstemmer=2.2.0
  - sortedcontainers=2.4.0
  - stack_data=0.6.2
  - tblib=3.0.0
  - tk=8.6.13
  - toml=0.10.2
  - tomli=2.0.2
  - tomlkit=0.13.2
  - toolz=1.0.0
  - tornado=6.4.1
  - tqdm=4.67.0
  - traitlets=5.14.3
  - typer=0.12.5
  - typer-slim=0.12.5
  - typer-slim-standard=0.12.5
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - tzdata=2024b
  - ukkonen=1.0.1
  - unicodedata2=15.1.0
  - urllib3=2.2.3
  - virtualenv=20.27.1
  - wayland=1.23.1
  - wcwidth=0.2.13
  - wheel=0.44.0
  - xarray=2024.10.0
  - xcb-util=0.4.1
  - xcb-util-cursor=0.1.5
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.1
  - xcb-util-renderutil=0.3.10
  - xcb-util-wm=0.4.2
  - xkeyboard-config=2.43
  - xorg-libice=1.1.1
  - xorg-libsm=1.2.4
  - xorg-libx11=1.8.10
  - xorg-libxau=1.0.11
  - xorg-libxcomposite=0.4.6
  - xorg-libxcursor=1.2.3
  - xorg-libxdamage=1.1.6
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxfixes=6.0.1
  - xorg-libxi=1.8.2
  - xorg-libxrandr=1.5.4
  - xorg-libxrender=0.9.11
  - xorg-libxtst=1.2.5
  - xorg-libxxf86vm=1.1.5
  - xorg-xextproto=7.3.0
  - xorg-xorgproto=2024.1
  - xyzservices=2024.9.0
  - xz=5.2.6
  - yaml=0.2.5
  - zict=3.0.0
  - zipp=3.20.2
  - zlib=1.3.1
  - zstandard=0.23.0
  - zstd=1.5.6
  - pip:
      - coverage==7.6.4
      - flake8-pyproject==1.2.3
      - pytest-cov==6.0.0
