channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.10
  - click>=7.1.2
  - Jinja2>=3.0.1
  - matplotlib>=3.2.1
  - netCDF4>=1.5.3
  - numpy>=1.18.2
  - pandas>=1.0.3
  - pathlib>=1.0.1
  - pytest>=6.2.1
  - regex>=2020.11.13
  - scipy>=1.4.1
  - xarray>=0.16.1
  - pip
  - pip:
    # add pip requirements here if needed.
