channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.10
  - pip>=22.3
  # runtime
  - click>=7.1.2
  - Jinja2>=3.0.1
  - matplotlib>=3.2.1
  - netCDF4>=1.5.3
  - numpy>=1.18.2
  - pathlib>=1.0.1
  - pandas>=1.0.3
  - pytest>=6.2.1
  - regex>=2020.11.13
  - scipy>=1.4.1
  - xarray>=0.16.1
  # development
  - black>=22.8.0
  - codespell>=2.2.2
  - flake8>=5.0.4
  - flake8-black
  - ipdb
  - ipython
  - isort>=5
  - mypy
  - pre-commit>=2.19.0
  - pre-commit-hooks>=4.3.0
  - pydocstyle>=6.1.1
  - pylint>=2.6.0
  - rope
  - rstcheck>=6.1.1
  - pip:
    # development
    - flake8-pyproject
    - pytest-cov
